/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject2;


import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AddTrainee extends javax.swing.JFrame {
  
    /**
     * Creates new form AddTrainee
     */
    public AddTrainee() {
        initComponents();
        setTitle("Add Trainee");
        setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ID_txt = new javax.swing.JTextField();
        Age_txt = new javax.swing.JTextField();
        GPA_txt = new javax.swing.JTextField();
        AcadYear_txt = new javax.swing.JTextField();
        Add_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Name_txt = new javax.swing.JTextField();
        Uni_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel2.setText("University Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel3.setText("Academic Year");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 468, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel4.setText("GPA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        jLabel5.setText("Add Trainee");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 230, 60));
        getContentPane().add(ID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 141, 181, -1));
        getContentPane().add(Age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 181, -1));
        getContentPane().add(GPA_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 181, -1));

        AcadYear_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcadYear_txtActionPerformed(evt);
            }
        });
        getContentPane().add(AcadYear_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 466, 181, -1));

        Add_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/plus.png"))); // NOI18N
        Add_btn.setText("Add");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 531, -1, 35));

        Cancel_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/cancel.png"))); // NOI18N
        Cancel_btn.setText("Cancel");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, 40));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 143, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel7.setText("Age");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        Name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 181, -1));
        getContentPane().add(Uni_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 181, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/Website-Landing-Page-Best-Practices-1520x800again.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 590, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcadYear_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcadYear_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcadYear_txtActionPerformed

    private void Name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_txtActionPerformed

    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
         setVisible(false);
           new Home().setVisible(true);
    }//GEN-LAST:event_Cancel_btnActionPerformed

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        Admin a = new Admin();
        Trainee t = new Trainee();
     
        if(ID_txt.getText().equals("")||Name_txt.getText().equals("") || Age_txt.getText().equals("") || Uni_txt.getText().equals("") || GPA_txt.getText().equals("") || AcadYear_txt.getText().equals("") ) 
        
            {
              JOptionPane.showMessageDialog(null , "Please fill in all the information","ERROR", JOptionPane.ERROR_MESSAGE);
              return;
            }
         try{
               
           Integer.parseInt(ID_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter an Integer for ID","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }
         try{
               
            Integer.parseInt(Age_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter an Integer for Age","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }
         try
         {
         Double.parseDouble(GPA_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter a Number for GPA","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }
          try{
               
           Integer.parseInt(AcadYear_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter an Integer for Academic Year","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }  
               
        if(Integer.parseInt(ID_txt.getText()) < 0  )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid ID ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
        if(Integer.parseInt(Age_txt.getText()) < 0 || Integer.parseInt(Age_txt.getText()) <19 )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid Age ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
        if(Integer.parseInt(GPA_txt.getText()) < 0 || Integer.parseInt(GPA_txt.getText()) >4 )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid GPA ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
        if(Integer.parseInt(AcadYear_txt.getText()) < 0 || Integer.parseInt(AcadYear_txt.getText()) >7 )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid Academic Year ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
        t.setID(Integer.parseInt(ID_txt.getText()));
        t.setName(Name_txt.getText());
        t.setAge(Integer.parseInt(Age_txt.getText()));
        t.setUni_name(Uni_txt.getText());
        t.setGPA(Double.parseDouble(GPA_txt.getText()));
        t.setAcademic_year(Integer.parseInt(AcadYear_txt.getText()));
       
       
        if( a.Add_Trainees(t))
        {
        JOptionPane.showMessageDialog(null , "Added succussefully");
        }
        else
        {
            
            JOptionPane.showMessageDialog(null , "ID already exists");
            return;
        }
        
       ID_txt.setText(null);
       Name_txt.setText(null);
       Age_txt.setText(null);
       Uni_txt.setText(null);
       GPA_txt.setText(null);
       AcadYear_txt.setText(null);
        
        
    }//GEN-LAST:event_Add_btnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTrainee().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddTrainee().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AcadYear_txt;
    private javax.swing.JButton Add_btn;
    private javax.swing.JTextField Age_txt;
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JTextField GPA_txt;
    private javax.swing.JTextField ID_txt;
    private javax.swing.JTextField Name_txt;
    private javax.swing.JTextField Uni_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
