/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject2;


/**
 *
 * @author DELL
 */
public class CalculateSalary extends javax.swing.JFrame {

    /**
     * Creates new form CalculateSalary
     */
    public CalculateSalary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Calc_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        WorkHours_txt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        jLabel1.setText("Calculate Salary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 137, -1, -1));

        ID_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(ID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 138, 162, 25));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel4.setText("Working Hours");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 206, -1, -1));

        Calc_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Calc_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/calculator.png"))); // NOI18N
        Calc_btn.setText("Calculate");
        Calc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Calc_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 369, -1, 34));

        Cancel_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/cancel.png"))); // NOI18N
        Cancel_btn.setText("Cancel");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 369, -1, 34));

        WorkHours_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WorkHours_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkHours_txtActionPerformed(evt);
            }
        });
        getContentPane().add(WorkHours_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 208, 160, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel5.setText("Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/Website-Landing-Page-Best-Practices-1520x800again.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 770, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
        setVisible(false);
           new Home().setVisible(true);
    }//GEN-LAST:event_Cancel_btnActionPerformed

    private void WorkHours_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkHours_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkHours_txtActionPerformed

    private void Calc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_btnActionPerformed
        Admin a= new Admin ();
        a.insert_salaries(ID_txt, WorkHours_txt, jComboBox1, jComboBox3, jComboBox2);//entering the textfields and comboboxs required
              
    }//GEN-LAST:event_Calc_btnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calc_btn;
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JTextField ID_txt;
    private javax.swing.JTextField WorkHours_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
