/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject2;


import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DeleteEngineer extends javax.swing.JFrame {
    
    /**
     * Creates new form DeleteEngineer
     */
    public DeleteEngineer() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EngID_txt = new javax.swing.JTextField();
        Delete_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        jLabel1.setText("Delete Engineer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 34, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel2.setText("Engineer ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        EngID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngID_txtActionPerformed(evt);
            }
        });
        getContentPane().add(EngID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 121, 25));

        Delete_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/delete.png"))); // NOI18N
        Delete_btn.setText("Delete");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        Cancel_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/cancel.png"))); // NOI18N
        Cancel_btn.setText("Cancel");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/Website-Landing-Page-Best-Practices-1520x800again.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 970, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EngID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngID_txtActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
 
       if(EngID_txt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Engineer ID");
            return;
        }
         try{
               
            Integer.parseInt(EngID_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please enter a number for ID","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           }
            Admin a = new Admin();
            Engineer eng = a.search_Engineer(Integer.parseInt(EngID_txt.getText()));
          
             if(eng == null)
        {
            JOptionPane.showMessageDialog(this, "ID doesn't exist");
            EngID_txt.setText(null);
            
        }

             else
             {
                 
                 if(a.Delete_Engineer(Integer.parseInt (EngID_txt.getText()))){
            JOptionPane.showMessageDialog(Delete_btn, "Deleted Successfully");
            EngID_txt.setText(null);
            }
            else 
            {
                JOptionPane.showMessageDialog(Delete_btn, "Error in deletion");
                EngID_txt.setText(null);
            }
             }

    }//GEN-LAST:event_Delete_btnActionPerformed

   
    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_Cancel_btnActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEngineer().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DeleteEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DeleteEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DeleteEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DeleteEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DeleteEngineer().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JTextField EngID_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
