/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject2;


import javax.swing.JOptionPane;


/**
 *
 * @author DELL
 */

public class DeleteTrainee extends javax.swing.JFrame {
      
    /**
     * Creates new form DeleteTrainee
     */
    public DeleteTrainee() {
        initComponents();
   
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TraineeID_lbl = new javax.swing.JLabel();
        TraineeID_txt = new javax.swing.JTextField();
        DeleteTrainee_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cancel_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TraineeID_lbl.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        TraineeID_lbl.setText("Trainee ID");
        getContentPane().add(TraineeID_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 33));

        TraineeID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TraineeID_txtActionPerformed(evt);
            }
        });
        getContentPane().add(TraineeID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 165, 26));

        DeleteTrainee_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        DeleteTrainee_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/delete.png"))); // NOI18N
        DeleteTrainee_btn.setText("Delete");
        DeleteTrainee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTrainee_btnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteTrainee_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 40));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Trainee");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 260, 60));

        Cancel_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/cancel.png"))); // NOI18N
        Cancel_btn.setText("Cancel");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/Website-Landing-Page-Best-Practices-1520x800again.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 1060, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TraineeID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TraineeID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TraineeID_txtActionPerformed

    private void DeleteTrainee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTrainee_btnActionPerformed
        Admin a=new Admin();
        if(TraineeID_txt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Trainee ID");
            return;
                    
                  
            
        }
         try{
               
            Integer.parseInt(TraineeID_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please enter a number for ID","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           }
        Trainee trainee = a.search_trainee(Integer.parseInt(TraineeID_txt.getText()));
        if(trainee == null)
        {
            JOptionPane.showMessageDialog(this, "ID doesn't exist");
            TraineeID_txt.setText(null);
            
        }
        else
        {
            
            if(a.Delete_Trainee(Integer.parseInt(TraineeID_txt.getText()))){
            JOptionPane.showMessageDialog(DeleteTrainee_btn, "Deleted");
            TraineeID_txt.setText(null);
            }
            else 
            {
                JOptionPane.showMessageDialog(DeleteTrainee_btn, "Error in deletion");
                TraineeID_txt.setText(null);
            }
          
        }
    }//GEN-LAST:event_DeleteTrainee_btnActionPerformed
  
    
    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
        setVisible(false);
           new Home().setVisible(true);
    }//GEN-LAST:event_Cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteTrainee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JButton DeleteTrainee_btn;
    private javax.swing.JLabel TraineeID_lbl;
    private javax.swing.JTextField TraineeID_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
