/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject2;


import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class EditTrainee extends javax.swing.JFrame {
    
    /**
     * Creates new form EditTrainee
     */
    public EditTrainee() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID_txt = new javax.swing.JTextField();
        Name_txt = new javax.swing.JTextField();
        Age_txt = new javax.swing.JTextField();
        UniName_txt = new javax.swing.JTextField();
        GPA_txt = new javax.swing.JTextField();
        AcadYear_txt = new javax.swing.JTextField();
        Update_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 127, 25, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 185, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel3.setText("Age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 245, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel4.setText("Univeristy Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 319, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel5.setText("GPA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 397, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel6.setText("Academic Year");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 474, -1, -1));

        ID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_txtActionPerformed(evt);
            }
        });
        getContentPane().add(ID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 129, 166, -1));
        getContentPane().add(Name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 187, 170, -1));

        Age_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 247, 170, -1));
        getContentPane().add(UniName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 321, 170, -1));
        getContentPane().add(GPA_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 399, 170, -1));
        getContentPane().add(AcadYear_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 476, 174, -1));

        Update_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/reload (1).png"))); // NOI18N
        Update_btn.setText("Update");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 549, -1, -1));

        Cancel_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/cancel.png"))); // NOI18N
        Cancel_btn.setText("Cancel");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 549, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        jLabel7.setText("Update Trainee");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject2/binoculars.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 120, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject2/operations-manager-job-description1.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_txtActionPerformed

    private void Age_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_txtActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
         Admin a = new Admin();
    
        Trainee trainee = new Trainee();
        if(Name_txt.getText().equals("")||Age_txt.getText().equals("") || UniName_txt.getText().equals("") || GPA_txt.equals("") || AcadYear_txt.getText().equals("")) 
 
            {
              JOptionPane.showMessageDialog(null , "Error, All text fields must have information");
            }
        try{
               
           Integer.parseInt(ID_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter an Integer for ID","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }
        
            try{
               
            Integer.parseInt(Age_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter an Integer for Age","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }
             try{
               
           Double.parseDouble(GPA_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter a Number for GPA","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }
          try{
               
           Integer.parseInt(AcadYear_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter an Integer for Academic Year","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }  
               
        if(Integer.parseInt(ID_txt.getText()) < 0  )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid ID ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
         
        if(Integer.parseInt(Age_txt.getText()) < 0 || Integer.parseInt(Age_txt.getText()) <19 )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid Age ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
     if(Integer.parseInt(GPA_txt.getText()) < 0 || Integer.parseInt(GPA_txt.getText()) >4 )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid GPA ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        if(Integer.parseInt(AcadYear_txt.getText()) < 0 || Integer.parseInt(AcadYear_txt.getText()) >7 )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid Academic Year ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        
        
            int ID  = Integer.parseInt(ID_txt.getText());
 
        trainee.setName(Name_txt.getText());
        trainee.setAge(Integer.parseInt(Age_txt.getText()));
       trainee.setUni_name(UniName_txt.getText());
       trainee.setGPA(Double.parseDouble(GPA_txt.getText()));
       trainee.setAcademic_year(Integer.parseInt(AcadYear_txt.getText()));
       
     if( a.Update_Trainee(ID,trainee))
        {
        JOptionPane.showMessageDialog(null , "Updated succussefully");
         
        
 
        }
        else
        {
            JOptionPane.showMessageDialog(null , "Error in update");
        }
       ID_txt.setText(null);
       Name_txt.setText(null);
       Age_txt.setText(null);
       UniName_txt.setText(null);
       GPA_txt.setText(null);
       AcadYear_txt.setText(null);
     
 
       
 
                             
    }//GEN-LAST:event_Update_btnActionPerformed

    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_Cancel_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // TODO add your handling code here:
        Admin a= new Admin();
        if(ID_txt.getText().equals(""))
        {
             JOptionPane.showMessageDialog(this, "Please enter an ID");
             return;
        }
        try
        {
            Integer.parseInt(ID_txt.getText());
        }
        catch(NumberFormatException ex)
                {
                    JOptionPane.showMessageDialog(this, "Please enter an integer for ID");
                    return;
                }
        int ID =Integer.parseInt(ID_txt.getText());
        Trainee trainee = a.search_trainee(ID);
        if(trainee== null)
        {
            JOptionPane.showMessageDialog(this, "ID doesn't exist");
            ID_txt.setText(null);
            
        }
        else
        {
             JOptionPane.showMessageDialog(this, "ID exists"); 
             Name_txt.setText(trainee.name);
             Age_txt.setText(trainee.age+ "");
             UniName_txt.setText(trainee.getUni_name());
             GPA_txt.setText(trainee.getGPA()+"");
             AcadYear_txt.setText(trainee.getAcademic_year()+"");
             
             
        }
        
    
             
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
  
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTrainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTrainee().setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AcadYear_txt;
    private javax.swing.JTextField Age_txt;
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JTextField GPA_txt;
    private javax.swing.JTextField ID_txt;
    private javax.swing.JTextField Name_txt;
    private javax.swing.JTextField UniName_txt;
    private javax.swing.JButton Update_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
