/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject2;


import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class EditEngineer extends javax.swing.JFrame {
    
    /**
     * Creates new form EditEngineer
     */
    public EditEngineer() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID_txt = new javax.swing.JTextField();
        Name_txt = new javax.swing.JTextField();
        Age_txt = new javax.swing.JTextField();
        Search_btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Engineer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 35, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 159, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 251, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jLabel6.setText("Position");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 496, -1, -1));
        getContentPane().add(ID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 162, 165, -1));
        getContentPane().add(Name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 254, 165, -1));
        getContentPane().add(Age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 343, 165, -1));

        Search_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/search.png"))); // NOI18N
        Search_btn.setText("Search");
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 155, -1, -1));

        Update_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/reload (1).png"))); // NOI18N
        Update_btn.setText("Update");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 581, -1, -1));

        Cancel_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/cancel.png"))); // NOI18N
        Cancel_btn.setText("Cancel");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 581, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Team Member", "Team Leader", "Manager" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 493, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/Website-Landing-Page-Best-Practices-1520x800again.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 570, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
         Admin a = new Admin();
    
        Engineer eng = new Engineer();
        Grade g;
        
         if(Name_txt.getText().equals("")||Age_txt.getText().equals("") ||  jComboBox1.equals("")) 
 
            {
              JOptionPane.showMessageDialog(null , "Error, All text fields must have information");
              return;
            }
         try{
               
           Integer.parseInt(ID_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter an Integer for ID","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }
          try{
               
            Integer.parseInt(Age_txt.getText());
            
         }
           catch(NumberFormatException ex )
           {
               JOptionPane.showMessageDialog(rootPane , "Please Enter an Integer for Age","ERROR", JOptionPane.ERROR_MESSAGE);
               return;
           
           }
          
           if(Integer.parseInt(ID_txt.getText()) < 0  )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid ID ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
        if(Integer.parseInt(Age_txt.getText()) < 0 || Integer.parseInt(Age_txt.getText()) <19 )
        {
             JOptionPane.showMessageDialog(rootPane , "You Entered an Invalid age ","ERROR", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
          
        int ID  = Integer.parseInt(ID_txt.getText());
        eng.setName(Name_txt.getText());
        eng.setAge(Integer.parseInt(Age_txt.getText()));
        g = new Grade (jComboBox1.getSelectedItem().toString());
        eng.setGrade(g);
             
 
 
        if( a.Update_Engineer(ID,eng))
        {
        JOptionPane.showMessageDialog(null , "Updated succussefully");
       
 
        }
        else
        {
            JOptionPane.showMessageDialog(null , "Error in update");
            return;
        }
       ID_txt.setText(null);
       Name_txt.setText(null);
       Age_txt.setText(null);
     
 
        
 
    }//GEN-LAST:event_Update_btnActionPerformed

    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed
     
        if(ID_txt.getText().equals(""))
        {
             JOptionPane.showMessageDialog(null , "Please enter an ID ");
             return;
        }
        try
        {
            Integer.parseInt(ID_txt.getText());
        }
        catch(NumberFormatException ex)
        {
            
             JOptionPane.showMessageDialog(null , "Please enter an integer for ID ");
             return;
        }
       Admin a= new Admin();
                int ID =Integer.parseInt(ID_txt.getText());
        Engineer eng = a.search_Engineer(ID);
        if(eng== null)
        {
            JOptionPane.showMessageDialog(this, "ID doesn't exist");
            ID_txt.setText(null);
            
        }
        else
        {
             JOptionPane.showMessageDialog(this, "ID exists"); 
             Name_txt.setText(eng.name);
             Age_txt.setText(eng.age+ "");
             jComboBox1.setSelectedItem(eng.getGrade().getPosition());
             
             
             
        }
        
      
    }//GEN-LAST:event_Search_btnActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEngineer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEngineer().setVisible(true);
            }
        });
    }

    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_Cancel_btnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_txt;
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JTextField ID_txt;
    private javax.swing.JTextField Name_txt;
    private javax.swing.JButton Search_btn;
    private javax.swing.JButton Update_btn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
