/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject2;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username_label = new javax.swing.JLabel();
        Password_label = new javax.swing.JLabel();
        Username_txt = new javax.swing.JTextField();
        Password_txt = new javax.swing.JPasswordField();
        Login_btn = new javax.swing.JButton();
        Exit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username_label.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Username_label.setForeground(new java.awt.Color(255, 255, 255));
        Username_label.setText("Username");
        getContentPane().add(Username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        Password_label.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Password_label.setForeground(new java.awt.Color(255, 255, 255));
        Password_label.setText("Password");
        getContentPane().add(Password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        Username_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_txtActionPerformed(evt);
            }
        });
        getContentPane().add(Username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 185, -1));
        getContentPane().add(Password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 190, -1));

        Login_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/login (1).png"))); // NOI18N
        Login_btn.setText("Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        Exit_btn.setFont(new java.awt.Font("Sylfaen", 1, 21)); // NOI18N
        Exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/exit.png"))); // NOI18N
        Exit_btn.setText("Exit");
        Exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/AdobeStock_269993681-scaled-e1589887594204nn.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_txtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Username_txtActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        // TODO add your handling code here
     if(Username_txt.getText().equals("") || Password_txt.getText().equals(""))
             {
                  JOptionPane.showMessageDialog(null,"Please enter your username and password");
       
             }
         else
     {
        Admin admin = new Admin();
        admin.setUsername(Username_txt.getText());
        admin.setPassword(Password_txt.getText());
    if( admin.Login())
       { 
           setVisible(false);
           new Home().setVisible(true);
           
           //JOptionPane.showMessageDialog(null,"Welcomee");
       }
       else
       {
           JOptionPane.showMessageDialog(null,"Wrong username or password");
       }
     }
                
    }//GEN-LAST:event_Login_btnActionPerformed

    private void Exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btnActionPerformed
      System.exit(0);
    }//GEN-LAST:event_Exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_btn;
    private javax.swing.JButton Login_btn;
    private javax.swing.JLabel Password_label;
    private javax.swing.JPasswordField Password_txt;
    private javax.swing.JLabel Username_label;
    private javax.swing.JTextField Username_txt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
